from transformers import pipeline
from textblob import TextBlob

text = "The media will not show the magnitude of this crowd. Even I, when I turned on today, I looked, and I saw thousands of people here, but you don't see hundreds of thousands of people behind you because they don't want to show that. We have hundreds of thousands of people here, and I just want them to be recognized by the fake news media. Turn your cameras please and show what's really happening out here because these people are not going to take it any longer. They're not going to take it any longer. Go ahead. Turn your cameras, please. Would you show? They came from all over the world, actually, but they came from all over our country. I just really want to see what they do. I just want to see how they covered. I've never seen anything like it. But it would be really great if we could be covered fairly by the media. The media is the biggest problem we have as far as I'm concerned, single biggest problem, the fake news and the big tech. Big tech is now coming into their own. We beat them four years ago. We surprised them. We took them by surprise and this year, they rigged an election. They rigged it like they've never rigged an election before. By the way, last night, they didn't do a bad job either, if you notice. I'm honest. I just, again, I want to thank you. It's just a great honor to have this kind of crowd and to be before you. Hundreds of thousands of American patriots are committed to the honesty of our elections and the integrity of our glorious Republic. All of us here today do not want to see our election victory stolen by emboldened radical left Democrats, which is what they're doing and stolen by the fake news media. That's what they've done and what they're doing. We will never give up. We will never concede, it doesn't happen. You don't concede when there's theft involved."

#text = "The Importance of Being Earnest, a Trivial Comedy for Serious People is a play by Oscar Wilde, the last of his four drawing-room plays, following Lady Windermere's Fan (1892), A Woman of No Importance (1893) and An Ideal Husband (1895). First performed on 14 February 1895 at the St James's Theatre in London, it is a farcical comedy depicting the tangled affairs of two young men about town who lead double lives to evade unwanted social obligations, both assuming the name Ernest while wooing the two young women of their affections."

#text = "Further expansion of the NATO infrastructure and the beginning of military development in Ukraine's territories are unacceptable for us. The problem, of course, is not NATO itself – it is only an instrument of US foreign policy. The problem is that in the territories adjacent to us – territories that were historically ours, I emphasise – an 'anti-Russia' hostile to us is being created, placed under full external control; [it] is intensively settled by the armed forces of NATO countries and is supplied with the most modern weapons"

#text = "The green Bandera-style T-shirt proclaimed a resilience plan of ten points in its Rada. In reality, it needs a personal resilience plan with just one point: sniff less and stay closer to reality. Meanwhile, the Supreme Betrayal of Ukraine is sitting on packed suitcases, anticipating difficult developments (see point 1)."

#text = "This is fake as fuck"

text = "Mathematics is a field of study that discovers and organizes methods, theories and theorems that are developed and proved for the needs of empirical sciences and mathematics itself. There are many areas of mathematics, which include number theory (the study of numbers), algebra (the study of formulas and related structures), geometry (the study of shapes and spaces that contain them), analysis (the study of continuous changes), and set theory (presently used as a foundation for all mathematics)."

blob = TextBlob(text)

subjectivity_score = blob.sentiment.subjectivity

print("Subjectivity score:", subjectivity_score)